import { defineStore } from "pinia";

export const useMyStore=defineStore('myStore',{
    state:()=>({

products: [
    {
        "id": 168,
        "slug": "product-163-pywwi",
        "category_id": 11,
        "product_name": "product 163",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230915182131image_190x230-254.png",
        "price": 100,
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 24,
        "todays_deal": 1,
        "has_variant": 0,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false
    },
    {
        "id": 167,
        "slug": "product-162-kraj8",
        "category_id": 11,
        "product_name": "product 162",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/lhttps://www.embroiderybyjojo.com/public/images/20230915182238image_190x230-237.png",
        "price": 100,
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 34,
        "todays_deal": 1,
        "has_variant": 0,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false
    },
    {
        "id": 166,
        "slug": "product-161-w9dhl",
        "category_id": 11,
        "product_name": "product 161",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230915182210image_190x230-311.png",
        "price": 100,
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 22,
        "todays_deal": 1,
        "has_variant": 0,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false
    },
    {
        "id": 165,
        "slug": "product-160-3xdwq",
        "category_id": 11,
        "product_name": "product 160",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914174949image_190x230-307.png",
        "price": 100,
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 38,
        "todays_deal": 1,
        "has_variant": 0,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false
    },
    {
        "id": 164,
        "slug": "product-159-qzjig",
        "category_id": 11,
        "product_name": "product 159",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914174840image_190x230-474.png",
        "price": 100,
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 37,
        "todays_deal": 1,
        "has_variant": 0,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false
    },
    {
        "id": 163,
        "slug": "product-158-8c4w0",
        "category_id": 11,
        "product_name": "product 158",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914174748image_190x230-256.png",
        "price": 100,
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 28,
        "todays_deal": 1,
        "has_variant": 0,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false
    },
    {
        "id": 162,
        "slug": "product-157-wpmxz",
        "category_id": 11,
        "product_name": "product 157",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914174653image_190x230-389.png",
        "price": 100,
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 37,
        "todays_deal": 1,
        "has_variant": 0,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false
    },
    {
        "id": 161,
        "slug": "product-156-p38on",
        "category_id": 11,
        "product_name": "product 156",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914174543image_190x230-20.png",
        "price": 100,
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 37,
        "todays_deal": 1,
        "has_variant": 0,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false
    },
    {
        "id": 160,
        "slug": "product-155-urgcb",
        "category_id": 11,
        "product_name": "product 155",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914174430image_190x230-35.png",
        "price": 100,
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 43,
        "todays_deal": 1,
        "has_variant": 0,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false
    },
    {
        "id": 159,
        "slug": "product-154-efowa",
        "category_id": 11,
        "product_name": "product 154",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914174157image_190x230-211.png",
        "price": 100,
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 25,
        "todays_deal": 1,
        "has_variant": 0,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false
    },
    {
        "id": 158,
        "slug": "product-153-moupq",
        "category_id": 11,
        "product_name": "product 153",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914174053image_190x230-306.png",
        "price": 100,
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 16,
        "todays_deal": 1,
        "has_variant": 0,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false
    },
    {
        "id": 157,
        "slug": "product-152-yfnwz",
        "category_id": 11,
        "product_name": "product 152",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914173939image_190x230-166.png",
        "price": 100,
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 67,
        "todays_deal": 1,
        "has_variant": 0,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false
    },
    {
        "id": 156,
        "slug": "product-150-aeh7k",
        "category_id": 11,
        "product_name": "product 151",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914173818image_190x230-74.png",
        "price": 100,
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 34,
        "todays_deal": 1,
        "has_variant": 0,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false
    },
    {
        "id": 155,
        "slug": "product-150-jnay0",
        "category_id": 1,
        "product_name": "product 150",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914173720image_190x230-1.png",
        "price": 100,
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 34,
        "todays_deal": 1,
        "has_variant": 0,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false
    },
    {
        "id": 154,
        "slug": "product-149-4qfew",
        "category_id": 11,
        "product_name": "product 149",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914173604image_190x230-389.png",
        "price": 100,
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 35,
        "todays_deal": 1,
        "has_variant": 0,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false
    },
    {
        "id": 153,
        "slug": "product-148-tggtv",
        "category_id": 11,
        "product_name": "product 148",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914173504image_190x230-254.png",
        "price": 100,
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 35,
        "todays_deal": 1,
        "has_variant": 0,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false
    },
    {
        "id": 152,
        "slug": "product-147-r4xkt",
        "category_id": 11,
        "product_name": "product 147",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914173344image_190x230-234.png",
        "price": 100,
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 55,
        "todays_deal": 0,
        "has_variant": 0,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false
    },
    {
        "id": 151,
        "slug": "product-146-etosg",
        "category_id": 11,
        "product_name": "product 146",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914173213image_190x230-12.png",
        "price": 100,
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 33,
        "todays_deal": 1,
        "has_variant": 0,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false
    },
    {
        "id": 150,
        "slug": "product-145-b6qpm",
        "category_id": 11,
        "product_name": "product 145",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914173108image_190x230-361.png",
        "price": 100,
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 33,
        "todays_deal": 1,
        "has_variant": 0,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false
    },
    {
        "id": 149,
        "slug": "product-144-r0106",
        "category_id": 11,
        "product_name": "product 144",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914173020image_190x230-414.png",
        "price": 100,
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 35,
        "todays_deal": 1,
        "has_variant": 0,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false
    },
    {
        "id": 148,
        "slug": "product-143-0h7xs",
        "category_id": 11,
        "product_name": "product 143",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914172926image_190x230-187.png",
        "price": 100,
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 71,
        "todays_deal": 1,
        "has_variant": 0,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false
    },
    {
        "id": 147,
        "slug": "product-142-lgwfk",
        "category_id": 11,
        "product_name": "product 142",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914172812image_190x230-13.png",
        "price": 100,
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 35,
        "todays_deal": 1,
        "has_variant": 0,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false
    },
    {
        "id": 146,
        "slug": "product-141-3p0wr",
        "category_id": 11,
        "product_name": "product 141",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914172711image_190x230-25.png",
        "price": 100,
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 33,
        "todays_deal": 1,
        "has_variant": 0,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false
    },
    {
        "id": 145,
        "slug": "product-140-enusr",
        "category_id": 11,
        "product_name": "product 140",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914172602image_190x230-479.png",
        "price": 100,
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 35,
        "todays_deal": 1,
        "has_variant": 0,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false
    }
]
,
popular_categories: [
    {
        "id": 1,
        "slug": "category-four-yn5ad",
        "title": "Accessoires",
        "popular_image": "https://www.embroiderybyjojo.com/public/images/default/130x95_no_bg.png",
        "top_image": "https://www.embroiderybyjojo.com/public/images/default/80x60_no_bg.png"
    },
    {
        "id": 3,
        "slug": "category-six-n2bo7",
        "title": "Miscellaneous",
        "popular_image": "https://www.embroiderybyjojo.com/public/images/default/130x95_no_bg.png",
        "top_image": "https://www.embroiderybyjojo.com/public/images/default/80x60_no_bg.png"
    },
    {
        "id": 4,
        "slug": "category-seven-okccl",
        "title": "Paint By Number",
        "popular_image": "https://www.embroiderybyjojo.com/public/images/default/130x95_no_bg.png",
        "top_image": "https://www.embroiderybyjojo.com/public/images/default/80x60_no_bg.png"
    },
    {
        "id": 9,
        "slug": "category-two-jivat",
        "title": "Nature Morte",
        "popular_image": "https://www.embroiderybyjojo.com/public/images/default/130x95_no_bg.png",
        "top_image": "https://www.embroiderybyjojo.com/public/images/default/80x60_no_bg.png"
    },
    {
        "id": 10,
        "slug": "category-three-fhtpw",
        "title": "Landscapes",
        "popular_image": "https:\/\/www.embroiderybyjojo.com\/public\/images\/default\/130x95_no_bg.png",
        "top_image": "https://www.embroiderybyjojo.com/public/images/default/80x60_no_bg.png"
    }
],
today_deals: [
    {
        "id": 168,
        "slug": "product-163-pywwi",
        "category_id": 11,
        "product_name": "product 163",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230915182131image_190x230-254.png",
        "image_40x40": "https://www.embroiderybyjojo.com/public/images/20230915181808image_40x40_media_221.jpg",
        "is_approved": 1,
        "price": 100,
        "status": "published",
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 24,
        "todays_deal": 1,
        "has_variant": false,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false,
        "stock": [
            {
                "stock_variant": "",
                "current_stock": 0,
                "has_variant": false
            }
        ]
    },
    {
        "id": 167,
        "slug": "product-162-kraj8",
        "category_id": 11,
        "product_name": "product 162",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230915182238image_190x230-237.png",
        "image_40x40": "https://www.embroiderybyjojo.com/public/images/20230915181810image_40x40_media_94.jpg",
        "is_approved": 1,
        "price": 100,
        "status": "published",
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 34,
        "todays_deal": 1,
        "has_variant": false,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false,
        "stock": [
            {
                "stock_variant": "",
                "current_stock": 0,
                "has_variant": false
            }
        ]
    },
    {
        "id": 166,
        "slug": "product-161-w9dhl",
        "category_id": 11,
        "product_name": "product 161",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230915182210image_190x230-311.png",
        "image_40x40": "https://www.embroiderybyjojo.com/public/images/20230915181808image_40x40_media_182.jpg",
        "is_approved": 1,
        "price": 100,
        "status": "published",
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 22,
        "todays_deal": 1,
        "has_variant": false,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false,
        "stock": [
            {
                "stock_variant": "",
                "current_stock": 0,
                "has_variant": false
            }
        ]
    },
    {
        "id": 165,
        "slug": "product-160-3xdwq",
        "category_id": 11,
        "product_name": "product 160",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914174949image_190x230-307.png",
        "image_40x40": "https://www.embroiderybyjojo.com/public/images/20230914174359image_40x40_media_144.jpg",
        "is_approved": 1,
        "price": 100,
        "status": "published",
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 38,
        "todays_deal": 1,
        "has_variant": false,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false,
        "stock": [
            {
                "stock_variant": "",
                "current_stock": 0,
                "has_variant": false
            }
        ]
    },
    {
        "id": 164,
        "slug": "product-159-qzjig",
        "category_id": 11,
        "product_name": "product 159",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914174840image_190x230-474.png",
        "image_40x40": "https://www.embroiderybyjojo.com/public/images/20230914174401image_40x40_media_353.jpg",
        "is_approved": 1,
        "price": 100,
        "status": "published",
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 37,
        "todays_deal": 1,
        "has_variant": false,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false,
        "stock": [
            {
                "stock_variant": "",
                "current_stock": 0,
                "has_variant": false
            }
        ]
    },
    {
        "id": 163,
        "slug": "product-158-8c4w0",
        "category_id": 11,
        "product_name": "product 158",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914174748image_190x230-256.png",
        "image_40x40": "https://www.embroiderybyjojo.com/public/images/20230914174401image_40x40_media_239.jpg",
        "is_approved": 1,
        "price": 100,
        "status": "published",
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 28,
        "todays_deal": 1,
        "has_variant": false,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false,
        "stock": [
            {
                "stock_variant": "",
                "current_stock": 0,
                "has_variant": false
            }
        ]
    },
    {
        "id": 162,
        "slug": "product-157-wpmxz",
        "category_id": 11,
        "product_name": "product 157",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914174653image_190x230-389.png",
        "image_40x40": "https://www.embroiderybyjojo.com/public/images/20230914174401image_40x40_media_443.jpg",
        "is_approved": 1,
        "price": 100,
        "status": "published",
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 37,
        "todays_deal": 1,
        "has_variant": false,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false,
        "stock": [
            {
                "stock_variant": "",
                "current_stock": 0,
                "has_variant": false
            }
        ]
    },
    {
        "id": 161,
        "slug": "product-156-p38on",
        "category_id": 11,
        "product_name": "product 156",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914174543image_190x230-20.png",
        "image_40x40": "https://www.embroiderybyjojo.com/public/images/20230914174402image_40x40_media_475.jpg",
        "is_approved": 1,
        "price": 100,
        "status": "published",
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 37,
        "todays_deal": 1,
        "has_variant": false,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false,
        "stock": [
            {
                "stock_variant": "",
                "current_stock": 0,
                "has_variant": false
            }
        ]
    },
    {
        "id": 160,
        "slug": "product-155-urgcb",
        "category_id": 11,
        "product_name": "product 155",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914174430image_190x230-35.png",
        "image_40x40": "https://www.embroiderybyjojo.com/public/images/20230914174402image_40x40_media_19.jpg",
        "is_approved": 1,
        "price": 100,
        "status": "published",
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 43,
        "todays_deal": 1,
        "has_variant": false,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false,
        "stock": [
            {
                "stock_variant": "",
                "current_stock": 0,
                "has_variant": false
            }
        ]
    },
    {
        "id": 159,
        "slug": "product-154-efowa",
        "category_id": 11,
        "product_name": "product 154",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914174157image_190x230-211.png",
        "image_40x40": "https://www.embroiderybyjojo.com/public/images/20230914171730image_40x40_media_201.jpg",
        "is_approved": 1,
        "price": 100,
        "status": "published",
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 25,
        "todays_deal": 1,
        "has_variant": false,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false,
        "stock": [
            {
                "stock_variant": "",
                "current_stock": 0,
                "has_variant": false
            }
        ]
    },
    {
        "id": 158,
        "slug": "product-153-moupq",
        "category_id": 11,
        "product_name": "product 153",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914174053image_190x230-306.png",
        "image_40x40": "https://www.embroiderybyjojo.com/public/images/20230914171730image_40x40_media_283.jpg",
        "is_approved": 1,
        "price": 100,
        "status": "published",
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 16,
        "todays_deal": 1,
        "has_variant": false,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false,
        "stock": [
            {
                "stock_variant": "",
                "current_stock": 0,
                "has_variant": false
            }
        ]
    },
    {
        "id": 157,
        "slug": "product-152-yfnwz",
        "category_id": 11,
        "product_name": "product 152",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914173939image_190x230-166.png",
        "image_40x40": "https://www.embroiderybyjojo.com/public/images/20230914171730image_40x40_media_204.jpg",
        "is_approved": 1,
        "price": 100,
        "status": "published",
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 67,
        "todays_deal": 1,
        "has_variant": false,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false,
        "stock": [
            {
                "stock_variant": "",
                "current_stock": 0,
                "has_variant": false
            }
        ]
    },
    {
        "id": 156,
        "slug": "product-150-aeh7k",
        "category_id": 11,
        "product_name": "product 151",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914173818image_190x230-74.png",
        "image_40x40": "https://www.embroiderybyjojo.com/public/images/20230914171731image_40x40_media_278.jpg",
        "is_approved": 1,
        "price": 100,
        "status": "published",
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 34,
        "todays_deal": 1,
        "has_variant": false,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false,
        "stock": [
            {
                "stock_variant": "",
                "current_stock": 0,
                "has_variant": false
            }
        ]
    },
    {
        "id": 155,
        "slug": "product-150-jnay0",
        "category_id": 1,
        "product_name": "product 150",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914173720image_190x230-1.png",
        "image_40x40": "https://www.embroiderybyjojo.com/public/images/20230914171731image_40x40_media_278.jpg",
        "is_approved": 1,
        "price": 100,
        "status": "published",
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 34,
        "todays_deal": 1,
        "has_variant": false,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false,
        "stock": [
            {
                "stock_variant": "",
                "current_stock": 0,
                "has_variant": false
            }
        ]
    },
    {
        "id": 154,
        "slug": "product-149-4qfew",
        "category_id": 11,
        "product_name": "product 149",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914173604image_190x230-389.png",
        "image_40x40": "https://www.embroiderybyjojo.com/public/images/20230914171731image_40x40_media_75.jpg",
        "is_approved": 1,
        "price": 100,
        "status": "published",
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 35,
        "todays_deal": 1,
        "has_variant": false,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false,
        "stock": [
            {
                "stock_variant": "",
                "current_stock": 0,
                "has_variant": false
            }
        ]
    },
    {
        "id": 153,
        "slug": "product-148-tggtv",
        "category_id": 11,
        "product_name": "product 148",
        "special_discount_type": "",
        "special_discount_check": 0,
        "discount_percentage": 0,
        "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914173504image_190x230-254.png",
        "image_40x40": "https://www.embroiderybyjojo.com/public/images/20230914171732image_40x40_media_265.jpg",
        "is_approved": 1,
        "price": 100,
        "status": "published",
        "rating": 0,
        "reviews_count": 0,
        "current_stock": 0,
        "reward": 0,
        "minimum_order_quantity": 35,
        "todays_deal": 1,
        "has_variant": false,
        "user_wishlist": false,
        "is_catalog": false,
        "is_classified": false,
        "stock": [
            {
                "stock_variant": "",
                "current_stock": 0,
                "has_variant": false
            }
        ]
    }
],

   
        latest_products: [
            {
                "id": 168,
                "slug": "product-163-pywwi",
                "category_id": 11,
                "product_name": "product 163",
                "special_discount_type": "",
                "special_discount_check": 0,
                "discount_percentage": 0,
                "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230915182131image_190x230-254.png",
                "image_40x40": "https://www.embroiderybyjojo.com/public/images/20230915181808image_40x40_media_221.jpg",
                "is_approved": 1,
                "price": 100,
                "status": "published",
                "rating": 0,
                "reviews_count": 0,
                "current_stock": 0,
                "reward": 0,
                "minimum_order_quantity": 24,
                "todays_deal": 1,
                "has_variant": false,
                "user_wishlist": false,
                "is_catalog": false,
                "is_classified": false,
                "stock": [
                    {
                        "stock_variant": "",
                        "current_stock": 0,
                        "has_variant": false
                    }
                ]
            },
            {
                "id": 167,
                "slug": "product-162-kraj8",
                "category_id": 11,
                "product_name": "product 162",
                "special_discount_type": "",
                "special_discount_check": 0,
                "discount_percentage": 0,
                "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230915182238image_190x230-237.png",
                "image_40x40": "https://www.embroiderybyjojo.com/public/images/20230915181810image_40x40_media_94.jpg",
                "is_approved": 1,
                "price": 100,
                "status": "published",
                "rating": 0,
                "reviews_count": 0,
                "current_stock": 0,
                "reward": 0,
                "minimum_order_quantity": 34,
                "todays_deal": 1,
                "has_variant": false,
                "user_wishlist": false,
                "is_catalog": false,
                "is_classified": false,
                "stock": [
                    {
                        "stock_variant": "",
                        "current_stock": 0,
                        "has_variant": false
                    }
                ]
            },
            {
                "id": 166,
                "slug": "product-161-w9dhl",
                "category_id": 11,
                "product_name": "product 161",
                "special_discount_type": "",
                "special_discount_check": 0,
                "discount_percentage": 0,
                "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230915182210image_190x230-311.png",
                "image_40x40": "https://www.embroiderybyjojo.com/public/images/20230915181808image_40x40_media_182.jpg",
                "is_approved": 1,
                "price": 100,
                "status": "published",
                "rating": 0,
                "reviews_count": 0,
                "current_stock": 0,
                "reward": 0,
                "minimum_order_quantity": 22,
                "todays_deal": 1,
                "has_variant": false,
                "user_wishlist": false,
                "is_catalog": false,
                "is_classified": false,
                "stock": [
                    {
                        "stock_variant": "",
                        "current_stock": 0,
                        "has_variant": false
                    }
                ]
            },
            {
                "id": 165,
                "slug": "product-160-3xdwq",
                "category_id": 11,
                "product_name": "product 160",
                "special_discount_type": "",
                "special_discount_check": 0,
                "discount_percentage": 0,
                "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914174949image_190x230-307.png",
                "image_40x40": "https://www.embroiderybyjojo.com/public/images/20230914174359image_40x40_media_144.jpg",
                "is_approved": 1,
                "price": 100,
                "status": "published",
                "rating": 0,
                "reviews_count": 0,
                "current_stock": 0,
                "reward": 0,
                "minimum_order_quantity": 38,
                "todays_deal": 1,
                "has_variant": false,
                "user_wishlist": false,
                "is_catalog": false,
                "is_classified": false,
                "stock": [
                    {
                        "stock_variant": "",
                        "current_stock": 0,
                        "has_variant": false
                    }
                ]
            },
            {
                "id": 164,
                "slug": "product-159-qzjig",
                "category_id": 11,
                "product_name": "product 159",
                "special_discount_type": "",
                "special_discount_check": 0,
                "discount_percentage": 0,
                "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914174840image_190x230-474.png",
                "image_40x40": "https://www.embroiderybyjojo.com/public/images/20230914174401image_40x40_media_353.jpg",
                "is_approved": 1,
                "price": 100,
                "status": "published",
                "rating": 0,
                "reviews_count": 0,
                "current_stock": 0,
                "reward": 0,
                "minimum_order_quantity": 37,
                "todays_deal": 1,
                "has_variant": false,
                "user_wishlist": false,
                "is_catalog": false,
                "is_classified": false,
                "stock": [
                    {
                        "stock_variant": "",
                        "current_stock": 0,
                        "has_variant": false
                    }
                ]
            },
            {
                "id": 163,
                "slug": "product-158-8c4w0",
                "category_id": 11,
                "product_name": "product 158",
                "special_discount_type": "",
                "special_discount_check": 0,
                "discount_percentage": 0,
                "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914174748image_190x230-256.png",
                "image_40x40": "https://www.embroiderybyjojo.com/public/images/20230914174401image_40x40_media_239.jpg",
                "is_approved": 1,
                "price": 100,
                "status": "published",
                "rating": 0,
                "reviews_count": 0,
                "current_stock": 0,
                "reward": 0,
                "minimum_order_quantity": 28,
                "todays_deal": 1,
                "has_variant": false,
                "user_wishlist": false,
                "is_catalog": false,
                "is_classified": false,
                "stock": [
                    {
                        "stock_variant": "",
                        "current_stock": 0,
                        "has_variant": false
                    }
                ]
            }
        ],
        "blog-9": []
    ,
    
      
            top_categories: [
                {
                    "id": 1,
                    "slug": "category-four-yn5ad",
                    "title": "Accessoires",
                    "popular_image": "https://www.embroiderybyjojo.com/public/images/default/130x95_no_bg.png",
                    "top_image": "https://www.embroiderybyjojo.com/public/images/default/80x60_no_bg.png"
                },
                {
                    "id": 2,
                    "slug": "category-five-ndaew",
                    "title": "Loops Frames",
                    "popular_image": "https://www.embroiderybyjojo.com/public/images/default/130x95_no_bg.png",
                    "top_image": "https://www.embroiderybyjojo.com/public/images/default/80x60_no_bg.png"
                },
                {
                    "id": 3,
                    "slug": "category-six-n2bo7",
                    "title": "Miscellaneous",
                    "popular_image": "https://www.embroiderybyjojo.com/public/images/default/130x95_no_bg.png",
                    "top_image": "https://www.embroiderybyjojo.com/public/images/default/80x60_no_bg.png"
                },
                {
                    "id": 4,
                    "slug": "category-seven-okccl",
                    "title": "Paint By Number",
                    "popular_image": "https://www.embroiderybyjojo.com/public/images/default/130x95_no_bg.png",
                    "top_image": "https://www.embroiderybyjojo.com/public/images/default/80x60_no_bg.png"
                },
                {
                    "id": 11,
                    "slug": "category-one-kfs0j",
                    "title": "portraits",
                    "popular_image": "https://www.embroiderybyjojo.com/public/images/default/130x95_no_bg.png",
                    "top_image": "https://www.embroiderybyjojo.com/public/images/default/80x60_no_bg.png"
                }
            ],
            "category_sec_banner-5": "https://www.embroiderybyjojo.com/public/images/default/default-image-405x745.png",
            "category_sec_banner_url-5": "/",
            Accessoires: [
                {
                    "id": 155,
                    "slug": "product-150-jnay0",
                    "category_id": 1,
                    "product_name": "product 150",
                    "special_discount_type": "",
                    "special_discount_check": 0,
                    "discount_percentage": 0,
                    "image_190x230": "https:\/\/www.embroiderybyjojo.com\/public\/images\/20230914173720image_190x230-1.png",
                    "image_40x40": "https:\/\/www.embroiderybyjojo.com\/public\/images\/20230914171731image_40x40_media_278.jpg",
                    "is_approved": 1,
                    "price": 100,
                    "status": "published",
                    "rating": 0,
                    "reviews_count": 0,
                    "current_stock": 0,
                    "reward": 0,
                    "minimum_order_quantity": 34,
                    "todays_deal": 1,
                    "has_variant": false,
                    "user_wishlist": false,
                    "is_catalog": false,
                    "is_classified": false,
                    "stock": [
                        {
                            "stock_variant": "",
                            "current_stock": 0,
                            "has_variant": false
                        }
                    ]
                },
                {
                    "id": 1,
                    "slug": "demo-product-znkzt",
                    "category_id": 1,
                    "product_name": "Demo Product",
                    "special_discount_type": "flat",
                    "special_discount_check": 20,
                    "discount_percentage": 979,
                    "image_190x230": "https:\/\/www.embroiderybyjojo.com\/public\/images\/default\/190x230_no_bg.png",
                    "image_40x40": "https:\/\/www.embroiderybyjojo.com\/public\/images\/default\/default-image-40x40.png",
                    "is_approved": 1,
                    "price": 999,
                    "status": "published",
                    "rating": 0,
                    "reviews_count": 0,
                    "current_stock": 200,
                    "reward": 0,
                    "minimum_order_quantity": 1,
                    "todays_deal": 1,
                    "has_variant": false,
                    "user_wishlist": false,
                    "is_catalog": false,
                    "is_classified": false,
                    "stock": [
                        {
                            "stock_variant": "",
                            "current_stock": 200,
                            "has_variant": false
                        }
                    ]
                }
            ],
            gadget_product: {
                "id": 1,
                "parent_id": null,
                "position": null,
                "ordering": 0,
                "slug": "category-four-yn5ad",
                "commission": 0,
                "is_featured": 0,
                "status": 1,
                "icon": "",
                "logo_id": null,
                "logo": [],
                "banner_id": null,
                "banner": [],
                "created_at": "2022-01-31T16:15:12.000000Z",
                "updated_at": "2022-04-08T04:11:24.000000Z",
               
                "title": null,
                "name": "Accessoires"
            },
            best_selling_product: [
                {
                    "id": 168,
                    "slug": "product-163-pywwi",
                    "category_id": 11,
                    "product_name": "product 163",
                    "special_discount_type": "",
                    "special_discount_check": 0,
                    "discount_percentage": 0,
                    "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230915182131image_190x230-254.png",
                    "image_40x40": "https://www.embroiderybyjojo.com/public/images/20230915181808image_40x40_media_221.jpg",
                    "is_approved": 1,
                    "price": 100,
                    "status": "published",
                    "rating": 0,
                    "reviews_count": 0,
                    "current_stock": 0,
                    "reward": 0,
                    "minimum_order_quantity": 24,
                    "todays_deal": 1,
                    "has_variant": false,
                    "user_wishlist": false,
                    "is_catalog": false,
                    "is_classified": false,
                    "stock": [
                        {
                            "stock_variant": "",
                            "current_stock": 0,
                            "has_variant": false
                        }
                    ]
                },
                {
                    "id": 167,
                    "slug": "product-162-kraj8",
                    "category_id": 11,
                    "product_name": "product 162",
                    "special_discount_type": "",
                    "special_discount_check": 0,
                    "discount_percentage": 0,
                    "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230915182238image_190x230-237.png",
                    "image_40x40": "https://www.embroiderybyjojo.com/public/images/20230915181810image_40x40_media_94.jpg",
                    "is_approved": 1,
                    "price": 100,
                    "status": "published",
                    "rating": 0,
                    "reviews_count": 0,
                    "current_stock": 0,
                    "reward": 0,
                    "minimum_order_quantity": 34,
                    "todays_deal": 1,
                    "has_variant": false,
                    "user_wishlist": false,
                    "is_catalog": false,
                    "is_classified": false,
                    "stock": [
                        {
                            "stock_variant": "",
                            "current_stock": 0,
                            "has_variant": false
                        }
                    ]
                },
                {
                    "id": 166,
                    "slug": "product-161-w9dhl",
                    "category_id": 11,
                    "product_name": "product 161",
                    "special_discount_type": "",
                    "special_discount_check": 0,
                    "discount_percentage": 0,
                    "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230915182210image_190x230-311.png",
                    "image_40x40": "https://www.embroiderybyjojo.com/public/images/20230915181808image_40x40_media_182.jpg",
                    "is_approved": 1,
                    "price": 100,
                    "status": "published",
                    "rating": 0,
                    "reviews_count": 0,
                    "current_stock": 0,
                    "reward": 0,
                    "minimum_order_quantity": 22,
                    "todays_deal": 1,
                    "has_variant": false,
                    "user_wishlist": false,
                    "is_catalog": false,
                    "is_classified": false,
                    "stock": [
                        {
                            "stock_variant": "",
                            "current_stock": 0,
                            "has_variant": false
                        }
                    ]
                },
                {
                    "id": 165,
                    "slug": "product-160-3xdwq",
                    "category_id": 11,
                    "product_name": "product 160",
                    "special_discount_type": "",
                    "special_discount_check": 0,
                    "discount_percentage": 0,
                    "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914174949image_190x230-307.png",
                    "image_40x40": "https://www.embroiderybyjojo.com/public/images/20230914174359image_40x40_media_144.jpg",
                    "is_approved": 1,
                    "price": 100,
                    "status": "published",
                    "rating": 0,
                    "reviews_count": 0,
                    "current_stock": 0,
                    "reward": 0,
                    "minimum_order_quantity": 38,
                    "todays_deal": 1,
                    "has_variant": false,
                    "user_wishlist": false,
                    "is_catalog": false,
                    "is_classified": false,
                    "stock": [
                        {
                            "stock_variant": "",
                            "current_stock": 0,
                            "has_variant": false
                        }
                    ]
                },
                {
                    "id": 164,
                    "slug": "product-159-qzjig",
                    "category_id": 11,
                    "product_name": "product 159",
                    "special_discount_type": "",
                    "special_discount_check": 0,
                    "discount_percentage": 0,
                    "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914174840image_190x230-474.png",
                    "image_40x40": "https://www.embroiderybyjojo.com/public/images/20230914174401image_40x40_media_353.jpg",
                    "is_approved": 1,
                    "price": 100,
                    "status": "published",
                    "rating": 0,
                    "reviews_count": 0,
                    "current_stock": 0,
                    "reward": 0,
                    "minimum_order_quantity": 37,
                    "todays_deal": 1,
                    "has_variant": false,
                    "user_wishlist": false,
                    "is_catalog": false,
                    "is_classified": false,
                    "stock": [
                        {
                            "stock_variant": "",
                            "current_stock": 0,
                            "has_variant": false
                        }
                    ]
                },
                {
                    "id": 163,
                    "slug": "product-158-8c4w0",
                    "category_id": 11,
                    "product_name": "product 158",
                    "special_discount_type": "",
                    "special_discount_check": 0,
                    "discount_percentage": 0,
                    "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914174748image_190x230-256.png",
                    "image_40x40": "https://www.embroiderybyjojo.com/public/images/20230914174401image_40x40_media_239.jpg",
                    "is_approved": 1,
                    "price": 100,
                    "status": "published",
                    "rating": 0,
                    "reviews_count": 0,
                    "current_stock": 0,
                    "reward": 0,
                    "minimum_order_quantity": 28,
                    "todays_deal": 1,
                    "has_variant": false,
                    "user_wishlist": false,
                    "is_catalog": false,
                    "is_classified": false,
                    "stock": [
                        {
                            "stock_variant": "",
                            "current_stock": 0,
                            "has_variant": false
                        }
                    ]
                },
                {
                    "id": 162,
                    "slug": "product-157-wpmxz",
                    "category_id": 11,
                    "product_name": "product 157",
                    "special_discount_type": "",
                    "special_discount_check": 0,
                    "discount_percentage": 0,
                    "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914174653image_190x230-389.png",
                    "image_40x40": "https://www.embroiderybyjojo.com/public/images/20230914174401image_40x40_media_443.jpg",
                    "is_approved": 1,
                    "price": 100,
                    "status": "published",
                    "rating": 0,
                    "reviews_count": 0,
                    "current_stock": 0,
                    "reward": 0,
                    "minimum_order_quantity": 37,
                    "todays_deal": 1,
                    "has_variant": false,
                    "user_wishlist": false,
                    "is_catalog": false,
                    "is_classified": false,
                    "stock": [
                        {
                            "stock_variant": "",
                            "current_stock": 0,
                            "has_variant": false
                        }
                    ]
                },
                {
                    "id": 161,
                    "slug": "product-156-p38on",
                    "category_id": 11,
                    "product_name": "product 156",
                    "special_discount_type": "",
                    "special_discount_check": 0,
                    "discount_percentage": 0,
                    "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914174543image_190x230-20.png",
                    "image_40x40": "https://www.embroiderybyjojo.com/public/images/20230914174402image_40x40_media_475.jpg",
                    "is_approved": 1,
                    "price": 100,
                    "status": "published",
                    "rating": 0,
                    "reviews_count": 0,
                    "current_stock": 0,
                    "reward": 0,
                    "minimum_order_quantity": 37,
                    "todays_deal": 1,
                    "has_variant": false,
                    "user_wishlist": false,
                    "is_catalog": false,
                    "is_classified": false,
                    "stock": [
                        {
                            "stock_variant": "",
                            "current_stock": 0,
                            "has_variant": false
                        }
                    ]
                },
                {
                    "id": 160,
                    "slug": "product-155-urgcb",
                    "category_id": 11,
                    "product_name": "product 155",
                    "special_discount_type": "",
                    "special_discount_check": 0,
                    "discount_percentage": 0,
                    "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914174430image_190x230-35.png",
                    "image_40x40": "https://www.embroiderybyjojo.com/public/images/20230914174402image_40x40_media_19.jpg",
                    "is_approved": 1,
                    "price": 100,
                    "status": "published",
                    "rating": 0,
                    "reviews_count": 0,
                    "current_stock": 0,
                    "reward": 0,
                    "minimum_order_quantity": 43,
                    "todays_deal": 1,
                    "has_variant": false,
                    "user_wishlist": false,
                    "is_catalog": false,
                    "is_classified": false,
                    "stock": [
                        {
                            "stock_variant": "",
                            "current_stock": 0,
                            "has_variant": false
                        }
                    ]
                },
                {
                    "id": 159,
                    "slug": "product-154-efowa",
                    "category_id": 11,
                    "product_name": "product 154",
                    "special_discount_type": "",
                    "special_discount_check": 0,
                    "discount_percentage": 0,
                    "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914174157image_190x230-211.png",
                    "image_40x40": "https://www.embroiderybyjojo.com/public/images/20230914171730image_40x40_media_201.jpg",
                    "is_approved": 1,
                    "price": 100,
                    "status": "published",
                    "rating": 0,
                    "reviews_count": 0,
                    "current_stock": 0,
                    "reward": 0,
                    "minimum_order_quantity": 25,
                    "todays_deal": 1,
                    "has_variant": false,
                    "user_wishlist": false,
                    "is_catalog": false,
                    "is_classified": false,
                    "stock": [
                        {
                            "stock_variant": "",
                            "current_stock": 0,
                            "has_variant": false
                        }
                    ]
                },
                {
                    "id": 158,
                    "slug": "product-153-moupq",
                    "category_id": 11,
                    "product_name": "product 153",
                    "special_discount_type": "",
                    "special_discount_check": 0,
                    "discount_percentage": 0,
                    "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914174053image_190x230-306.png",
                    "image_40x40": "https://www.embroiderybyjojo.com/public/images/20230914171730image_40x40_media_283.jpg",
                    "is_approved": 1,
                    "price": 100,
                    "status": "published",
                    "rating": 0,
                    "reviews_count": 0,
                    "current_stock": 0,
                    "reward": 0,
                    "minimum_order_quantity": 16,
                    "todays_deal": 1,
                    "has_variant": false,
                    "user_wishlist": false,
                    "is_catalog": false,
                    "is_classified": false,
                    "stock": [
                        {
                            "stock_variant": "",
                            "current_stock": 0,
                            "has_variant": false
                        }
                    ]
                },
                {
                    "id": 157,
                    "slug": "product-152-yfnwz",
                    "category_id": 11,
                    "product_name": "product 152",
                    "special_discount_type": "",
                    "special_discount_check": 0,
                    "discount_percentage": 0,
                    "image_190x230": "https://www.embroiderybyjojo.com/public/images/20230914173939image_190x230-166.png",
                    "image_40x40": "https://www.embroiderybyjojo.com/public/images/20230914171730image_40x40_media_204.jpg",
                    "is_approved": 1,
                    "price": 100,
                    "status": "published",
                    "rating": 0,
                    "reviews_count": 0,
                    "current_stock": 0,
                    "reward": 0,
                    "minimum_order_quantity": 67,
                    "todays_deal": 1,
                    "has_variant": false,
                    "user_wishlist": false,
                    "is_catalog": false,
                    "is_classified": false,
                    "stock": [
                        {
                            "stock_variant": "",
                            "current_stock": 0,
                            "has_variant": false
                        }
                    ]
                }
            ],
        
    categories: [
        {
            "id": 1,
            "parent_id": null,
            "slug": "category-four-yn5ad",
            "title": "Accessoires",
            "icon": "",
            "child_categories": []
        },
        {
            "id": 2,
            "parent_id": null,
            "slug": "category-five-ndaew",
            "title": "Loops Frames",
            "icon": "",
            "child_categories": []
        },
        {
            "id": 3,
            "parent_id": null,
            "slug": "category-six-n2bo7",
            "title": "Miscellaneous",
            "icon": "",
            "child_categories": []
        },
        {
            "id": 4,
            "parent_id": null,
            "slug": "category-seven-okccl",
            "title": "Paint By Number",
            "icon": "",
            "child_categories": []
        },
        {
            "id": 9,
            "parent_id": null,
            "slug": "category-two-jivat",
            "title": "Nature Morte",
            "icon": "",
            "child_categories": []
        },
        {
            "id": 10,
            "parent_id": null,
            "slug": "category-three-fhtpw",
            "title": "Landscapes",
            "icon": "",
            "child_categories": []
        },
        {
            "id": 11,
            "parent_id": null,
            "slug": "category-one-kfs0j",
            "title": "portraits",
            "icon": "",
            "child_categories": []
        }
    ]

    }),
actions:{

}
})